services:
  takeme:
    image: takeme
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - takeme-instance:/usr/var/takeme-instance
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  takeme-instance:
