services:
  takeme:
    image: takeme
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - takeme-instance:/opt/TakeMe/instance

volumes:
  takeme-instance:
