"""empty message

Revision ID: 229543004f9e
Revises: e61ecff99129
Create Date: 2024-01-28 21:38:48.770917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229543004f9e'
down_revision = 'e61ecff99129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('taken_on',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('taken_on',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
