"""Update resource model 2

Revision ID: 96f3ea4d0f7a
Revises: e87895ca2185
Create Date: 2023-12-31 15:00:39.843944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f3ea4d0f7a'
down_revision = 'e87895ca2185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('taken_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('taken_on',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('taken_on',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('taken_by',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
