"""Update resource model

Revision ID: e87895ca2185
Revises: 
Create Date: 2023-12-31 00:17:03.733889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87895ca2185'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('taken_on', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('taken_on')
        batch_op.drop_column('resource_type')

    # ### end Alembic commands ###
